version: "3.3"
services:
    mysqldb:
        image: mysql:5.7
        restart: always
        container_name: neggo_mysql
        environment:
            MYSQL_DATABASE: 'neggo'
            MYSQL_USER: 'khoand'
            MYSQL_PASSWORD: '123456'
            MYSQL_ROOT_PASSWORD: '123456'
        ports:
            - '3306:3306'
        expose:
            - '3306'
        volumes:
            - my-db:/var/lib/mysql
    runner:
        build:
          context: ./runner
          dockerfile: ./Dockerfile
        container_name: runner
        restart: always
        ports: 
            - "3001:3000"
    client:
        build:
          context: ./client
          dockerfile: "./Dockerfile"
        restart: always
        container_name: neggo_client
        ports:
            - "4000:3000"
        volumes:
            - ./client:/neggo/client
            - /neggo/client/node_modules
    # mongodb:
    #     container_name: neggo_mongodb
    #     image: mongo
    #     command: "mongod --port 27017"
    #     ports:
    #         - 27017:27017
    #     restart: always
    #     volumes:
    #         - ./data-node:/data/db
networks:
 default:
   external:
     name: docker-localhost
volumes:
    my-db:
