version: "3.3"
services:
    mysqldb:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: 'neggo'
            # So you don't have to use root, but you can if you like
            MYSQL_USER: 'khoand'
            # You can use whatever password you like
            MYSQL_PASSWORD: '123456'
            # Password for root access
            MYSQL_ROOT_PASSWORD: '123456'
        ports:
            # <Port exposed> : < MySQL Port running inside container>
            - '3306:3306'
        expose:
            # Opens port 3306 on the container
            - '3306'
            # Where our data will be persisted
        volumes:
            - my-db:/var/lib/mysql
    client:
        build:
          context: ./client
          dockerfile: "./Dockerfile"
        restart: always
        container_name: neggo_client
        ports:
            - "4000:3000"
        volumes:
            - ./client:/neggo/client
            - /neggo/client/node_modules
    # mongodb:
    #     container_name: neggo_mongodb
    #     image: mongo
    #     command: "mongod --port 27017"
    #     ports:
    #         - 27017:27017
    #     restart: always
    #     volumes:
    #         - ./data-node:/data/db
networks:
 default:
   external:
     name: docker-localhost
volumes:
    my-db:
